import './globals.css'
import localFont from 'next/font/local'
import PageHeader from './components/page-header'
import PageFooter from './components/page-footer'

const orbiter = localFont({ 
  src: './fonts/TASAOrbiter/TASAOrbiterVF.woff2',
  subsets: ['latin'],
  variable: '--font-orbiter',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${orbiter.variable} font-sans`}>
                <div className='page-container'>
                    <PageHeader />
                    {children}
                    <PageFooter />
                </div>
            </body>
        </html>
    )
}
